config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
    resources :products, path: '/'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
      title: 'A',
      description: 'B'
    }
    
  belongs_to :category
  has_one_attached :photo
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  
  ORDER_BY = { 
    newest: 'created_at DESC',
    cheapest: 'price ASC',
    expensive: 'price DESC'
  }
  
 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end


  def edit
    category
  end


  def create
    @category = Category.new(category_params)

      if @category.save
        redirect_to categories_url, notice: "Category was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end


  def update
    if category.update(category_params)
      redirect_to categories_url, notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    category.destroy
    
    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
        @categories = Category.all.order(name: :asc).load_async
        @products = Product.all.with_attached_photo
        #filtrado para category_id
        if params[:category_id]
            @products = @products.where(category_id: params[:category_id])
        end
        #filtrado para max y min price
        if params[:min_price].present?
            @products = @products.where('price >= ?', params[:min_price])
        end
        if params[:max_price].present?
            @products = @products.where('price <= ?', params[:max_price])
        end

        #filtrado para title and descriotion
        if params[:query_text].present?
            @products = @products.search_full_text(params[:query_text])
        end

        # aqui evitamos evaluar el order_by.present? porque al  metodo fetch le agregamos que
        # si no esta presente un valor en order_by pues traiga por defecto 'created_at DESC' ver fetch

        if params[:order_by].present?
            order_by = Product::ORDER_BY.fetch(params[:order_by].to_sym, Product::ORDER_BY[:newest])
            #agregar al metodo orden las querys de hash dependiendo cual de las 3 esto es lo que pasa
            # @products = @products.order('created_at DESC')
            @products = @products.order(order_by).load_async
        end
        @pagy, @products = pagy_countless(@products, items: 12)
    end
    def show
        product
    end

    def new
        @product = Product.new
    end

    def edit
        product
    end

    def image
        @products = Product.all
    end

    def update
        product

        if @product.update(product_params)
            redirect_to products_path, notice: 'product was successfully updated.'
        else
            render :edit, status: :unprocessable_entity
        end   
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to products_path, notice: 'Product was successfully created'
        else
            render :new, status: :unprocessable_entity
        end
    end 

    def destroy
        product.destroy
    
        respond_to do |format|
          format.html { redirect_to products_url, notice: 'Product was deleted' }
          format.json { head :no_content }
        end
      end
    
    private

    def product_params
        params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product
        @product = Product.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <div>
      <%= link_to 'Edit Category', edit_category_path(category), class: 'btn btn-warning'%>
      <%= button_to "Delete product", category_path(category), method: :delete, class: 'btn btn-danger'%>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
        <%= error %>
    </div>    
  <%end%>
<div>
  <%= form.label :name%>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<div>
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>


<%= render partial: "category", collection: @categories %>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%=DateTime.now%>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do%>
    <%= category.name %>
<%end%>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <div>
            <%= error %>
        </div>    
    <%end%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>
    <div>
        <%= form.label :category_id %>
        <%=form.collection_select :category_id, Category.all.order(name: :asc), :id, :name%>
    </div>
    <div>
        <%= form.label :photo %>
        <%= form.file_field :photo %>
    </div>

    <%= form.submit 'Guardar' %>
<%end%>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: 'product', 'data-turbo-frame': '_top' do %>

        <span><%=product.title%></span>
        <strong><li><%=product.price%></li></strong>
        <%= image_tag product.photo, width:200 if product.photo.attached? %>

<%end%>

app/views/products/edit.html.erb
<h2>Editar</h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'categories' do %>
    <h1>Productos:</h1>

    <!-- form para max y min price -->
    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: 'search', onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
        <%= form.number_field :min_price, placeholder: 'min price', onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: 'max price', onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
        <%=form.select :order_by, options_for_select([['Recent', 'newest'], ['high cost', 'expensive'], ['low cost', 'cheapest']], params[:order_by]), {}, {onChange: 'this.form.requestSubmit()'}%>
    <%end%>
    
    <%= link_to 'All', products_path%>

    <%= render partial: 'category', collection: @categories %>

    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy %>
    <%end%>
    <!-- <%= render '/shared/imagesOnePunch' %> -->
<%end%>

app/views/products/new.html.erb
<h1>Add product</h1>

<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <div>
            <%= error %>
        </div>    
    <%end%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>

    <%= form.submit 'Add product' %>
<%end%>

app/views/products/show.html.erb
<%= image_tag @product.photo, width:200 if @product.photo.attached? %>

<h1 class='title'><%= @product.title %></h1>

<p class='description'> <%= @product.description %></p>

<span class='price'> <%= @product.price %></span>

<div>
    <br>
    <%= link_to 'Edit product', edit_product_path(@product), class: 'btn btn-warning'  %>
</div>

<!-- <%= button_to "Delete product", @product, method: :delete, class: 'btn btn-danger'%> -->
<%= button_to "Destroy", @product, method: :delete, form: { data: {turbo_confirm: 'Are you sure?'} } %>

app/views/shared/_flash.html.erb
<div class='flash-notice'>
  <%= notice %>  
</div>
<div class='flash-alert'>
  <%= alert %>
</div>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>Vendelo</h1>
<%end%>

<button ><%= link_to 'add product', new_product_path  %></button>
<button ><%= link_to 'category', categories_path  %></button>

app/views/shared/_imagesOnePunch.erb
<section>
  <%= image_tag 'imagen.jpg', class:'img'%>
  <%= image_tag 'imagen1.png', class:'img' %>
  <%= image_tag 'imagen2.jpg', class:'img' %>
  <%= image_tag 'imagen3.jpg', class:'img' %>
  <%= image_tag 'imagen4.webp', class:'img' %>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href= <% new_category_path%> >Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>